### ISSUE TITLE
Are Raven APM part of your repo ?

### ISSUE THREAD

**Issue by louisguitton** [teldridge11/RPM-AI-Agent#1]
Hi @teldridge11 ,
love your approach here, the paper and the code. 

I am looking at Raven Advanced Progressive Matrices, and was wondering if what you've implemented here are Raven APMs or something else (I've read about the old RPM, also Raven APM, Raven SPM and Raven CPM)?
I'm a bit lost

Thanks

**Comment by teldridge11** [comment]
@louisguitton  If I'm not mistaken, the difference between APM and SPM is just the level of complexity.  S (standard) problems are easier than A (advanced) problems.  C just means colored problems I believe.  The problems I'm using aren't from an official dataset, so it's tough to say what class they are.  I would guess that they are almost all S though, just due to the fact that they are 3x3 at the most, and aren't terribly difficult (although some are 😄).  Maybe a few could potentially be considered advanced, but I'm not sure.  I don't know enough about how the system works to really know...I'm far from an expert on any of this.

**Comment by louisguitton** [comment]
Thanks for your reply! Makes sense.

**Comment by teldridge11** [comment]
Great, let me know if you have any more questions!  Going to close this.
